version: '3'
services:
  app:
    container_name: node-server-container
    build: .
    ports:
      - 4000:3001
    links:
      - database
  database:
    container_name: mongo-container
    image: mongo
    restart: unless-stopped
    env_file: .env
    ports:
      - 27019:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: tanzim
#      MONGO_INITDB_ROOT_PASSWORD: root101
#      MONGO_INITDB_DATABASE: graphql-tutorial-db
    volumes:
      - ./mongo-volume:/data/db